//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgOpenGPS {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class gStr {
        internal static string gsStart;
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal gStr() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgOpenGPS.gStr", typeof(gStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AB Curve ähnelt.
        /// </summary>
        public static string gsABCurve {
            get {
                return ResourceManager.GetString("gsABCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AB Line ähnelt.
        /// </summary>
        public static string gsABline {
            get {
                return ResourceManager.GetString("gsABline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About... ähnelt.
        /// </summary>
        public static string gsAbout {
            get {
                return ResourceManager.GetString("gsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action Has Been Cancelled ähnelt.
        /// </summary>
        public static string gsActionHasBeenCancelled {
            get {
                return ResourceManager.GetString("gsActionHasBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actual ähnelt.
        /// </summary>
        public static string gsActual {
            get {
                return ResourceManager.GetString("gsActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Agressiveness ähnelt.
        /// </summary>
        public static string gsAgressiveness {
            get {
                return ResourceManager.GetString("gsAgressiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area ähnelt.
        /// </summary>
        public static string gsArea {
            get {
                return ResourceManager.GetString("gsArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure ? ähnelt.
        /// </summary>
        public static string gsAreYouSure {
            get {
                return ResourceManager.GetString("gsAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Steer Configuration ähnelt.
        /// </summary>
        public static string gsAutoSteerConfiguration {
            get {
                return ResourceManager.GetString("gsAutoSteerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AutoSteer Port ähnelt.
        /// </summary>
        public static string gsAutoSteerPort {
            get {
                return ResourceManager.GetString("gsAutoSteerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Based on Field: ähnelt.
        /// </summary>
        public static string gsBasedOnField {
            get {
                return ResourceManager.GetString("gsBasedOnField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boundary ähnelt.
        /// </summary>
        public static string gsBoundary {
            get {
                return ResourceManager.GetString("gsBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boundary Lines File Corrupt ähnelt.
        /// </summary>
        public static string gsBoundaryLineFilesAreCorrupt {
            get {
                return ResourceManager.GetString("gsBoundaryLineFilesAreCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boundary Contour ähnelt.
        /// </summary>
        public static string gsBoundaryMenu {
            get {
                return ResourceManager.GetString("gsBoundaryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die But Field Is Loaded ähnelt.
        /// </summary>
        public static string gsButFieldIsLoaded {
            get {
                return ResourceManager.GetString("gsButFieldIsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Centimeter ähnelt.
        /// </summary>
        public static string gsCentimeters {
            get {
                return ResourceManager.GetString("gsCentimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charts ähnelt.
        /// </summary>
        public static string gsCharts {
            get {
                return ResourceManager.GetString("gsCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose a different field ähnelt.
        /// </summary>
        public static string gsChooseADifferentField {
            get {
                return ResourceManager.GetString("gsChooseADifferentField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose a different name ähnelt.
        /// </summary>
        public static string gsChooseADifferentName {
            get {
                return ResourceManager.GetString("gsChooseADifferentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose or Build a Different one ähnelt.
        /// </summary>
        public static string gsChooseBuildDifferentone {
            get {
                return ResourceManager.GetString("gsChooseBuildDifferentone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string gsClose {
            get {
                return ResourceManager.GetString("gsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close All Windows First ähnelt.
        /// </summary>
        public static string gsCloseAllWindowsFirst {
            get {
                return ResourceManager.GetString("gsCloseAllWindowsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close Field First ähnelt.
        /// </summary>
        public static string gsCloseFieldFirst {
            get {
                return ResourceManager.GetString("gsCloseFieldFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colors ähnelt.
        /// </summary>
        public static string gsColors {
            get {
                return ResourceManager.GetString("gsColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Completely Delete Boundary ähnelt.
        /// </summary>
        public static string gsCompletelyDeleteBoundary {
            get {
                return ResourceManager.GetString("gsCompletelyDeleteBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contour File Corrupt ähnelt.
        /// </summary>
        public static string gsContourFileIsCorrupt {
            get {
                return ResourceManager.GetString("gsContourFileIsCorrupt", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contour On ähnelt.
        /// </summary>
        public static string gsContourOn {
            get {
                return ResourceManager.GetString("gsContourOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Valid Path ähnelt.
        /// </summary>
        public static string gsCouldntGenerateValidPath {
            get {
                return ResourceManager.GetString("gsCouldntGenerateValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create A Boundary First ähnelt.
        /// </summary>
        public static string gsCreateABoundaryFirst {
            get {
                return ResourceManager.GetString("gsCreateABoundaryFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create New Field ähnelt.
        /// </summary>
        public static string gsCreateNewField {
            get {
                return ResourceManager.GetString("gsCreateNewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current ähnelt.
        /// </summary>
        public static string gsCurrent {
            get {
                return ResourceManager.GetString("gsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Curve Line File Corrupt ähnelt.
        /// </summary>
        public static string gsCurveLineFileIsCorrupt {
            get {
                return ResourceManager.GetString("gsCurveLineFileIsCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Curve Not ON ähnelt.
        /// </summary>
        public static string gsCurveNotOn {
            get {
                return ResourceManager.GetString("gsCurveNotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete All Sections And Contours ähnelt.
        /// </summary>
        public static string gsDeleteAllContoursAndSections {
            get {
                return ResourceManager.GetString("gsDeleteAllContoursAndSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Applied Area ähnelt.
        /// </summary>
        public static string gsDeleteAppliedArea {
            get {
                return ResourceManager.GetString("gsDeleteAppliedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This action will delete all the boundaries. Do you want to continue? ähnelt.
        /// </summary>
        public static string gsDeleteBoundaryMapping {
            get {
                return ResourceManager.GetString("gsDeleteBoundaryMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Contour Paths ähnelt.
        /// </summary>
        public static string gsDeleteContourPaths {
            get {
                return ResourceManager.GetString("gsDeleteContourPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete For Sure? ähnelt.
        /// </summary>
        public static string gsDeleteForSure {
            get {
                return ResourceManager.GetString("gsDeleteForSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directories ähnelt.
        /// </summary>
        public static string gsDirectories {
            get {
                return ResourceManager.GetString("gsDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory Exists ähnelt.
        /// </summary>
        public static string gsDirectoryExists {
            get {
                return ResourceManager.GetString("gsDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distance ähnelt.
        /// </summary>
        public static string gsDistance {
            get {
                return ResourceManager.GetString("gsDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drive In ähnelt.
        /// </summary>
        public static string gsDriveIn {
            get {
                return ResourceManager.GetString("gsDriveIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drive Thru ähnelt.
        /// </summary>
        public static string gsDriveThru {
            get {
                return ResourceManager.GetString("gsDriveThru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driving ähnelt.
        /// </summary>
        public static string gsDriving {
            get {
                return ResourceManager.GetString("gsDriving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East ähnelt.
        /// </summary>
        public static string gsEast {
            get {
                return ResourceManager.GetString("gsEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit AB Curve ähnelt.
        /// </summary>
        public static string gsEditABCurve {
            get {
                return ResourceManager.GetString("gsEditABCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit AB Line ähnelt.
        /// </summary>
        public static string gsEditABLine {
            get {
                return ResourceManager.GetString("gsEditABLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Field Name ähnelt.
        /// </summary>
        public static string gsEditFieldName {
            get {
                return ResourceManager.GetString("gsEditFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counts ähnelt.
        /// </summary>
        public static string gsEncoderCounts {
            get {
                return ResourceManager.GetString("gsEncoderCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter Coordinates For Simulator ähnelt.
        /// </summary>
        public static string gsEnterCoordinatesForSimulator {
            get {
                return ResourceManager.GetString("gsEnterCoordinatesForSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter Field Name ähnelt.
        /// </summary>
        public static string gsEnterFieldName {
            get {
                return ResourceManager.GetString("gsEnterFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter Sim Coords ähnelt.
        /// </summary>
        public static string gsEnterSimCoords {
            get {
                return ResourceManager.GetString("gsEnterSimCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string gsError {
            get {
                return ResourceManager.GetString("gsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error reading KML ähnelt.
        /// </summary>
        public static string gsErrorreadingKML {
            get {
                return ResourceManager.GetString("gsErrorreadingKML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field ähnelt.
        /// </summary>
        public static string gsField {
            get {
                return ResourceManager.GetString("gsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field File is Corrupt ähnelt.
        /// </summary>
        public static string gsFieldFileIsCorrupt {
            get {
                return ResourceManager.GetString("gsFieldFileIsCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field Is Open ähnelt.
        /// </summary>
        public static string gsFieldIsOpen {
            get {
                return ResourceManager.GetString("gsFieldIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field Not Open ähnelt.
        /// </summary>
        public static string gsFieldNotOpen {
            get {
                return ResourceManager.GetString("gsFieldNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Error ähnelt.
        /// </summary>
        public static string gsFileError {
            get {
                return ResourceManager.GetString("gsFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flag By Lat Lon ähnelt.
        /// </summary>
        public static string gsFlagByLatLon {
            get {
                return ResourceManager.GetString("gsFlagByLatLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flag File Corrupt ähnelt.
        /// </summary>
        public static string gsFlagFileIsCorrupt {
            get {
                return ResourceManager.GetString("gsFlagFileIsCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For Now ähnelt.
        /// </summary>
        public static string gsForNow {
            get {
                return ResourceManager.GetString("gsForNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From Existing ähnelt.
        /// </summary>
        public static string gsFromExisting {
            get {
                return ResourceManager.GetString("gsFromExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From KML ähnelt.
        /// </summary>
        public static string gsFromKml {
            get {
                return ResourceManager.GetString("gsFromKml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guidance Stopped ähnelt.
        /// </summary>
        public static string gsGuidanceStopped {
            get {
                return ResourceManager.GetString("gsGuidanceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heading Chart ähnelt.
        /// </summary>
        public static string gsHeadingChart {
            get {
                return ResourceManager.GetString("gsHeadingChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Headland ähnelt.
        /// </summary>
        public static string gsHeadland {
            get {
                return ResourceManager.GetString("gsHeadland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create and Edit Headland ähnelt.
        /// </summary>
        public static string gsHeadlandForm {
            get {
                return ResourceManager.GetString("gsHeadlandForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string gsHelp {
            get {
                return ResourceManager.GetString("gsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If Wrong Direction Tap Vehicle ähnelt.
        /// </summary>
        public static string gsIfWrongDirectionTapVehicle {
            get {
                return ResourceManager.GetString("gsIfWrongDirectionTapVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inch ähnelt.
        /// </summary>
        public static string gsInches {
            get {
                return ResourceManager.GetString("gsInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inner ähnelt.
        /// </summary>
        public static string gsInner {
            get {
                return ResourceManager.GetString("gsInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die kmh ähnelt.
        /// </summary>
        public static string gsKMH {
            get {
                return ResourceManager.GetString("gsKMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string gsLanguage {
            get {
                return ResourceManager.GetString("gsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Machine Port ähnelt.
        /// </summary>
        public static string gsMachinePort {
            get {
                return ResourceManager.GetString("gsMachinePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Make Boundary Contours ähnelt.
        /// </summary>
        public static string gsMakeBoundaryContours {
            get {
                return ResourceManager.GetString("gsMakeBoundaryContours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual ähnelt.
        /// </summary>
        public static string gsManual {
            get {
                return ResourceManager.GetString("gsManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meters ähnelt.
        /// </summary>
        public static string gsMeters {
            get {
                return ResourceManager.GetString("gsMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing ABLInes File ähnelt.
        /// </summary>
        public static string gsMissingABLinesFile {
            get {
                return ResourceManager.GetString("gsMissingABLinesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing Boundary File ähnelt.
        /// </summary>
        public static string gsMissingBoundaryFile {
            get {
                return ResourceManager.GetString("gsMissingBoundaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing Contour File ähnelt.
        /// </summary>
        public static string gsMissingContourFile {
            get {
                return ResourceManager.GetString("gsMissingContourFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing Flag File ähnelt.
        /// </summary>
        public static string gsMissingFlagsFile {
            get {
                return ResourceManager.GetString("gsMissingFlagsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing Section File ähnelt.
        /// </summary>
        public static string gsMissingSectionFile {
            get {
                return ResourceManager.GetString("gsMissingSectionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mph ähnelt.
        /// </summary>
        public static string gsMPH {
            get {
                return ResourceManager.GetString("gsMPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NEast ähnelt.
        /// </summary>
        public static string gsN_East {
            get {
                return ResourceManager.GetString("gsN_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NWest ähnelt.
        /// </summary>
        public static string gsN_West {
            get {
                return ResourceManager.GetString("gsN_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string gsNew {
            get {
                return ResourceManager.GetString("gsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ABLine Active ähnelt.
        /// </summary>
        public static string gsNoABLineActive {
            get {
                return ResourceManager.GetString("gsNoABLineActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Boundary ähnelt.
        /// </summary>
        public static string gsNoBoundary {
            get {
                return ResourceManager.GetString("gsNoBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Fields Found ähnelt.
        /// </summary>
        public static string gsNoFieldsFound {
            get {
                return ResourceManager.GetString("gsNoFieldsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Guidance Lines ähnelt.
        /// </summary>
        public static string gsNoGuidanceLines {
            get {
                return ResourceManager.GetString("gsNoGuidanceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string gsNone {
            get {
                return ResourceManager.GetString("gsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None Used ähnelt.
        /// </summary>
        public static string gsNoneUsed {
            get {
                return ResourceManager.GetString("gsNoneUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North ähnelt.
        /// </summary>
        public static string gsNorth {
            get {
                return ResourceManager.GetString("gsNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Settings With IMU ähnelt.
        /// </summary>
        public static string gsNoSettingsWithIMU {
            get {
                return ResourceManager.GetString("gsNoSettingsWithIMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nothing Deleted ähnelt.
        /// </summary>
        public static string gsNothingDeleted {
            get {
                return ResourceManager.GetString("gsNothingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        public static string gsOffset {
            get {
                return ResourceManager.GetString("gsOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset Fix ähnelt.
        /// </summary>
        public static string gsOffsetFix {
            get {
                return ResourceManager.GetString("gsOffsetFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string gsOpen {
            get {
                return ResourceManager.GetString("gsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outer ähnelt.
        /// </summary>
        public static string gsOuter {
            get {
                return ResourceManager.GetString("gsOuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overshoot Reduction ähnelt.
        /// </summary>
        public static string gsOvershootReduction {
            get {
                return ResourceManager.GetString("gsOvershootReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass # ähnelt.
        /// </summary>
        public static string gsPass {
            get {
                return ResourceManager.GetString("gsPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passes ähnelt.
        /// </summary>
        public static string gsPasses {
            get {
                return ResourceManager.GetString("gsPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Past End Of Curve ähnelt.
        /// </summary>
        public static string gsPastEndOfCurve {
            get {
                return ResourceManager.GetString("gsPastEndOfCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        public static string gsPause {
            get {
                return ResourceManager.GetString("gsPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please Enter ABLine ähnelt.
        /// </summary>
        public static string gsPleaseEnterABLine {
            get {
                return ResourceManager.GetString("gsPleaseEnterABLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pressure (bar) ähnelt.
        /// </summary>
        public static string gsPressureSensorValueLabel {
            get {
                return ResourceManager.GetString("gsPressureSensorValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem Making Path ähnelt.
        /// </summary>
        public static string gsProblemMakingPath {
            get {
                return ResourceManager.GetString("gsProblemMakingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program Will Exit Please Restart ähnelt.
        /// </summary>
        public static string gsProgramWillExitPleaseRestart {
            get {
                return ResourceManager.GetString("gsProgramWillExitPleaseRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really Reset Everything ähnelt.
        /// </summary>
        public static string gsReallyResetEverything {
            get {
                return ResourceManager.GetString("gsReallyResetEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Record ähnelt.
        /// </summary>
        public static string gsRecord {
            get {
                return ResourceManager.GetString("gsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recorded Path File Corrupt ähnelt.
        /// </summary>
        public static string gsRecordedPathFileIsCorrupt {
            get {
                return ResourceManager.GetString("gsRecordedPathFileIsCorrupt", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recorded Path File Corrupt ähnelt.
        /// </summary>
        public static string gsToolTrackcurveFileIsCorrupt
        {
            get
            {
                return ResourceManager.GetString("gsToolTrackcurveFileIsCorrupt", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recorded Path ähnelt.
        /// </summary>
        public static string gsRecordedPathMenu {
            get {
                return ResourceManager.GetString("gsRecordedPathMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset All ähnelt.
        /// </summary>
        public static string gsResetAll {
            get {
                return ResourceManager.GetString("gsResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset All For Sure? ähnelt.
        /// </summary>
        public static string gsResetAllForSure {
            get {
                return ResourceManager.GetString("gsResetAllForSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resume ähnelt.
        /// </summary>
        public static string gsResume {
            get {
                return ResourceManager.GetString("gsResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SE ähnelt.
        /// </summary>
        public static string gsS_East {
            get {
                return ResourceManager.GetString("gsS_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SW ähnelt.
        /// </summary>
        public static string gsS_West {
            get {
                return ResourceManager.GetString("gsS_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save and Return ähnelt.
        /// </summary>
        public static string gsSaveAndReturn {
            get {
                return ResourceManager.GetString("gsSaveAndReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save As ähnelt.
        /// </summary>
        public static string gsSaveAs {
            get {
                return ResourceManager.GetString("gsSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sent To Machine Module ähnelt.
        /// </summary>
        public static string gsSentToMachineModule {
            get {
                return ResourceManager.GetString("gsSentToMachineModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SetPoint ähnelt.
        /// </summary>
        public static string gsSetPoint {
            get {
                return ResourceManager.GetString("gsSetPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shift GPS Position (cm) ähnelt.
        /// </summary>
        public static string gsShiftGPSPosition {
            get {
                return ResourceManager.GetString("gsShiftGPSPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simulator On ähnelt.
        /// </summary>
        public static string gsSimulatorOn {
            get {
                return ResourceManager.GetString("gsSimulatorOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slow Down Below ähnelt.
        /// </summary>
        public static string gsSlowDownBelow {
            get {
                return ResourceManager.GetString("gsSlowDownBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smooth AB Curve ähnelt.
        /// </summary>
        public static string gsSmoothABCurve {
            get {
                return ResourceManager.GetString("gsSmoothABCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort ähnelt.
        /// </summary>
        public static string gsSort {
            get {
                return ResourceManager.GetString("gsSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South ähnelt.
        /// </summary>
        public static string gsSouth {
            get {
                return ResourceManager.GetString("gsSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spacing (cm) ähnelt.
        /// </summary>
        public static string gsSpacing {
            get {
                return ResourceManager.GetString("gsSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start or Delete A Boundary ähnelt.
        /// </summary>
        public static string gsStartDeleteABoundary {
            get {
                return ResourceManager.GetString("gsStartDeleteABoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start New Field ähnelt.
        /// </summary>
        public static string gsStartNewField {
            get {
                return ResourceManager.GetString("gsStartNewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steer Charts ähnelt.
        /// </summary>
        public static string gsSteerChart {
            get {
                return ResourceManager.GetString("gsSteerChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Steer Wizard ähnelt.
        /// </summary>
        public static string gsSteerWizard {
            get {
                return ResourceManager.GetString("gsSteerWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop Record Pause Boundary ähnelt.
        /// </summary>
        public static string gsStopRecordPauseBoundary {
            get {
                return ResourceManager.GetString("gsStopRecordPauseBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To File ähnelt.
        /// </summary>
        public static string gsToFile {
            get {
                return ResourceManager.GetString("gsToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too Fast ähnelt.
        /// </summary>
        public static string gsTooFast {
            get {
                return ResourceManager.GetString("gsTooFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top Field View ähnelt.
        /// </summary>
        public static string gsTopFieldView {
            get {
                return ResourceManager.GetString("gsTopFieldView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tram Lines ähnelt.
        /// </summary>
        public static string gsTramLines {
            get {
                return ResourceManager.GetString("gsTramLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turn AB Curve On ähnelt.
        /// </summary>
        public static string gsTurnABCurveOn {
            get {
                return ResourceManager.GetString("gsTurnABCurveOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turn On Contour of Make AB Line ähnelt.
        /// </summary>
        public static string gsTurnOnContourOrMakeABLine {
            get {
                return ResourceManager.GetString("gsTurnOnContourOrMakeABLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Selected ähnelt.
        /// </summary>
        public static string gsUseSelected {
            get {
                return ResourceManager.GetString("gsUseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebCam ähnelt.
        /// </summary>
        public static string gsWebCam {
            get {
                return ResourceManager.GetString("gsWebCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West ähnelt.
        /// </summary>
        public static string gsWest {
            get {
                return ResourceManager.GetString("gsWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Still Open ähnelt.
        /// </summary>
        public static string gsWindowsStillOpen {
            get {
                return ResourceManager.GetString("gsWindowsStillOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wizards ähnelt.
        /// </summary>
        public static string gsWizards {
            get {
                return ResourceManager.GetString("gsWizards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XTE Chart ähnelt.
        /// </summary>
        public static string gsXTEChart {
            get {
                return ResourceManager.GetString("gsXTEChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.youtube.com/watch?v=iN2cZ8avHag ähnelt.
        /// </summary>
        public static string v_AboutIntro {
            get {
                return ResourceManager.GetString("v_AboutIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.youtube.com/watch?v=fE3TPRIRSFg ähnelt.
        /// </summary>
        public static string v_RecordedPathForm {
            get {
                return ResourceManager.GetString("v_RecordedPathForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.youtube.com/watch?v=3SdvYgx8HHc ähnelt.
        /// </summary>
        public static string v_SteerSettingsForm {
            get {
                return ResourceManager.GetString("v_SteerSettingsForm", resourceCulture);
            }
        }
    }
}
